---

#- name: "Upgrade all packages"
#  apt: upgrade=yes 
#  become: true
#  become_method: sudo

- name: Add Sublime Text apt key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: true

- name: Add Sublime Text apt repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
  become: true

- name: Add Microsoft GPG key
  apt_key:
    file: /tmp/microsoft.asc
    state: present
  become: true

- name: Add VS Code repository
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: true  

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: "Installing Packages"
  package:
    name:
      - gobuster
      - autorecon
      - terminator
      - iptables-persistent
      - rclone
      - mingw-w64
      - python3-wsgidav
      - chisel
      - bloodhoung
      - gitleaks
      - feroxbuster
      - flameshot
      - ligolo-ng
      - sublime-text
      - code
    state: latest
  become: true
  become_method: sudo

  
