---
- name: Update nmap scripts
  become: yes
  command: nmap --script-updatedb

- name: Update database
  become: yes
  command: updatedb

- name: Searchsploit Update
  become: yes
  command: searchsploit -u

- name: Check if rockyou.txt.gz exists
  stat:
    path: /usr/share/wordlists/rockyou.txt.gz
  register: rockyou_gz_stat

- name: Decompress rockyou.txt if it exists
  become: yes
  command: gzip -d /usr/share/wordlists/rockyou.txt.gz
  when: rockyou_gz_stat.stat.exists

- name: fix scrolling in vmware
  lineinfile:
    path: ~/.zhrc
    line: 'imwheel -b "4 5" > /dev/null 2>&1'
    create: yes



